[package]
name = "pid-loop"
description = "PID loop for `no_std` targets"
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]
edition = "2021"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/dotcypress/pid-loop"
version = "0.0.2"
